Add en-US rule for em-dashes
typograf/typograf pull request #316
Opened 2019-01-20 00:14 UTC by azangru

2019-01-21 11:25 UTC, hcodes commented
Спасибо, посмотрю на днях.

2019-01-21 12:13 UTC, azangru commented
В англоязычной традиции с тире (em-dash, которое используется в привычном значении как разделительный синтаксический знак) все сложно: даже в рамках одной локали (особенно американской) возможны два варианта: 1) пробелы вокруг тире не ставятся; 2) пробелы вокруг тире ставятся.  Первый вариант более традиционный (напр., так в The Chicago Manual of Style); второй, кажется, шире распространен в интернете (напр., его придерживаются в The New York Times).

В этом пул-реквесте используется второй вариант. Возможно, в правило нужно передавать какие-то опции, которые позволят выбирать один из двух вариантов. Или считать, что если заменяемый знак стоит после пробела, значит, в данном тексте надо использовать пробелы вокруг тире.

2019-01-22 19:21 UTC, hcodes requested changes

2019-01-22 19:21 UTC, hcodes commented on docs/RULES.en-US.md
> -| 44. | [ru/dash/centuries](../src/rules/ru/dash/centuries.js) | Hyphen to dash in centuries | 310 |  | ✓ |
Просьба убрать изменения из папки docs/, я их при выпуске новой версии добавлю.

2019-01-22 19:21 UTC, hcodes commented on src/rules/en-US/dash/main.js
> +        const re = new RegExp(`(${spaceBefore})(${dashes})(${spaceAfter})`, 'g');
Лишние скобки у `spaceBefore`.

2019-01-23 22:13 UTC, azangru commented on src/rules/en-US/dash/main.js
> +        const re = new RegExp(`(${spaceBefore})(${dashes})(${spaceAfter})`, 'g');
Спасибо, исправил.

2019-01-24 10:35 UTC, merged