feat: add settings to common/space/delRepeatN
typograf/typograf pull request #336
Opened 2019-10-07 13:29 UTC by tplk

2019-10-07 13:31 UTC, tplk commented
Как я понял, на данный момент тесты не поддерживают изменение настроек правила.
Думаю, стоить добавить возможность указывать значения под конкретные тест кейсы.

2019-10-07 13:45 UTC, hcodes requested changes

2019-10-07 13:45 UTC, hcodes commented on src/rules/common/space/delRepeatN.js
> +        const replaceValue = '\n'.repeat(maxConsecutiveLineBreaks);
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String/repeat
`repeat` в IE не поддерживается.

2019-10-07 14:00 UTC, tplk commented on src/rules/common/space/delRepeatN.js
> +        const replaceValue = '\n'.repeat(maxConsecutiveLineBreaks);
я вижу хэлпер в классе Typograf (https://github.com/typograf/typograf/blob/dev/src/typograf.js#L120), его можно использовать?

2019-10-07 14:02 UTC, hcodes commented on src/rules/common/space/delRepeatN.js
> +        const replaceValue = '\n'.repeat(maxConsecutiveLineBreaks);
Можно.

2019-10-07 17:09 UTC, tplk commented on src/rules/common/space/delRepeatN.js
> +        const consecutiveLineBreaksRegex = new RegExp(`\n{${maxConsecutiveLineBreaks + 1},}`, 'g');
@hcodes 
Поддержки литералов в ИЕ ведь тоже нет. Это бабель преобразует?
https://caniuse.com/#feat=template-literals

2019-10-08 07:49 UTC, hcodes approved these changes

2019-10-08 07:50 UTC, hcodes commented on src/rules/common/space/delRepeatN.js
> +        const consecutiveLineBreaksRegex = new RegExp(`\n{${maxConsecutiveLineBreaks + 1},}`, 'g');
Ага, Babel.

2019-10-10 06:28 UTC, merged

2019-10-10 06:28 UTC, hcodes commented
Релиз отведу позже.