Fix afterComma before quotes
typograf/typograf pull request #420
Opened 2022-12-28 16:05 UTC by yacodes

Fixes adding unnecessary space after comma and before quote in several scenarios.

The bug can be reproduced within the fiddle: https://typograf.github.io/#!text=%E2%80%9CHello%20world%2C%E2%80%9D%20said%20Michael
```
“Hello world,” said Michael. → “Hello world, ” said Michael.
                                            ┬ 
space is unnecessary here ──────────────────┘
```

2023-01-06 10:37 UTC, hcodes requested changes

2023-01-06 10:37 UTC, hcodes commented on src/rules/common/space/afterComma.js
> +            new RegExp('(.),([^)",:.?\\s\\/\\\\' + privateLabel + (quotes.right || quotes) + '])', 'g'),
```js
(quotes.right)
```

quotes использовать по умолчанию не нужно.

2023-01-09 12:45 UTC, yacodes commented on src/rules/common/space/afterComma.js
> +            new RegExp('(.),([^)",:.?\\s\\/\\\\' + privateLabel + (quotes.right || quotes) + '])', 'g'),
В ситуациях, когда `locale === "common"`, значение `context.getData('quote')` это строка с кавычками (`«‹»›„“‟”"`), а не объект с ключами `right` и `left`. В этом случае необходимо использовать строковое значение со всеми кавычками, иначе пробел всё ещё будет возникать перед ними.

2023-01-09 12:55 UTC, yacodes commented on src/rules/common/space/afterComma.js
> +            new RegExp('(.),([^)",:.?\\s\\/\\\\' + privateLabel + (quotes.right || quotes) + '])', 'g'),
Обновил ветку до последнего `dev`, но вижу там такое же поведение.

2023-01-09 21:41 UTC, hcodes approved these changes

2023-01-09 21:43 UTC, hcodes commented on src/rules/common/space/afterComma.js
> +            new RegExp('(.),([^)",:.?\\s\\/\\\\' + privateLabel + (quotes.right || quotes) + '])', 'g'),
Не очевидный вариант, пока ок, подумаю позже как лучше сделать. Если правок больше, то вливаю.

2023-01-10 15:12 UTC, yacodes commented on src/rules/common/space/afterComma.js
> +            new RegExp('(.),([^)",:.?\\s\\/\\\\' + privateLabel + (quotes.right || quotes) + '])', 'g'),
Можно использовать более явную конструкцию, например:
```ts
const quote = context.getData('quote');
const quotes = typeof quote === 'string' ? quote as DataCommonQuote : (quote as DataQuote).right;
return text.replace(
    new RegExp('(.),([^)",:.?\\s\\/\\\\' + privateLabel + quotes + '])', 'g'),
    ($0, $1, $2) => isDigit($1) && isDigit($2) ? $0 : $1 + ', ' + $2
);
```

2023-01-12 12:44 UTC, hcodes commented on src/rules/common/space/afterComma.js
> +            new RegExp('(.),([^)",:.?\\s\\/\\\\' + privateLabel + (quotes.right || quotes) + '])', 'g'),
Ага, так яснее.

2023-01-12 14:20 UTC, yacodes commented on src/rules/common/space/afterComma.js
> +            new RegExp('(.),([^)",:.?\\s\\/\\\\' + privateLabel + (quotes.right || quotes) + '])', 'g'),
Обновил PR кодом выше.

2023-01-16 11:09 UTC, merged

2023-02-03 14:33 UTC, yacodes commented
@hcodes Привет! Возможно ли сделать релиз новой версии Типографа с этим PR?

2023-02-03 14:50 UTC, hcodes commented
Не могу добраться, попробую выделить время в ближайшие выходные.

2023-03-24 08:35 UTC, yacodes commented
@hcodes Привет! Хочу напомнить о своей просьбе сделать релиз новой версии, пожалуйста :)

2023-04-01 08:04 UTC, hcodes commented
Выпустил! @yacodes

2023-04-03 11:59 UTC, yacodes commented
@hcodes Ура, спасибо большое!