Предложение: конфигурация списка коротких слов с неразрывным пробелом
typograf/typograf pull request #435
Opened 2023-09-07 10:04 UTC by vintagentleman

Привет, @hcodes! Большое спасибо за классный инструмент, в команде пользуемся им постоянно.

Есть предложение по улучшению правила `shortWord`. Сейчас оно позволяет переопределить длину токенов, после которых неразрывный пробел нужно ставить. Однако семантика при этом не учитывается.

С этим есть несколько проблем:

- Пробел может оказаться неразрывным после полнозначных слов («мы», «it», «my» и т. д.). Особенно актуально для англ. локали, где высокочастотных коротких слов довольно много.
- При настройках по умолчанию (`lengthShortWord: 2`) неразрывный пробел не ставится, например, перед частицей not и артиклем the, где его отсутствие странно. Однако увеличение порога длины токена усугубляет первую проблему.

Кажется более оптимальным ориентироваться на грамматику: неразрывный пробел уместен в первую очередь после служебных слов (предлогов и артиклей в составе словосочетаний, а также союзов и частиц).

Я добавил списки для рус. и англ. локалей и настройку, которая включает использование этих списков вместо значения `lengthShortWord`

2023-09-12 14:20 UTC, hcodes commented
Спасибо за PR! Хотелось бы по умолчанию использовать новую настройку из PR. Пока не пойму как две настройки соединить.

2023-09-12 16:03 UTC, vintagentleman commented
Да, сейчас `lengthShortWord` и `useShortWordList` взаимоисключающие. А в каком случае может понадобиться, чтобы работали обе настройки?

2023-09-17 13:51 UTC, hcodes requested changes

2023-09-17 13:51 UTC, hcodes commented on src/rules/common/nbsp/afterShortWord.ts
> +        if (useShortWordList) {
В условие нужно добавить проверку на наличие словаря

2023-09-18 15:38 UTC, vintagentleman commented on src/rules/common/nbsp/afterShortWord.ts
> +        if (useShortWordList) {
Спасибо. Добавил

2023-09-19 14:25 UTC, hcodes approved these changes

2023-09-19 14:27 UTC, merged